### ISSUE TITLE
Cannot create map for fully interactive grid 

### ISSUE THREAD

**Issue by RELNO** [doorleyr/grid_geojson#3]
When running a full grid creation (below), get: 
```
ine 48, in <module>
    meta_map = json.dumps(grasbrook_grid.int_to_meta_map)
AttributeError: 'Grid' object has no attribute 'int_to_meta_map'

```

```
import json
import os
import sys
import requests


file_dir = os.path.dirname('grid_geojson')
sys.path.append(file_dir)
from module.grid_geojson import *  # nopep8


top_left_lon = 10.01129157249875
top_left_lat = 53.53380541749196

nrows = 78
ncols = 44

rotation = 145.5


cell_size = 16
crs_epsg = '31468'

properties = {
    'id': [i for i in range(nrows*ncols)],
    'usage': [0 for i in range(nrows*ncols)],
    'height': [-100 for i in range(nrows*ncols)],
    'pop_density': [2 for i in range(nrows*ncols)]}
crs_epsg = '31468'

grasbrook_grid = Grid(top_left_lon, top_left_lat, rotation,
                      crs_epsg, cell_size, nrows, ncols)

meta_map = json.dumps(grasbrook_grid.int_to_meta_map)


grid_geo = grasbrook_grid.get_grid_geojson(properties)

# Convert to string format
grid_geo_str = json.dumps(grid_geo)
f = open("results.json", "w+")
f.write(grid_geo_str)
f.close()

f = open("map.json", "w+")
f.write(meta_map)
f.close()

```

**Comment by RELNO** [comment]
solved with the following -- had to use extend grid to full, which is not very clear for simple fully interactive cases. Can you add this example to the repo as `grassbrook_full_interactive`? 

```
import json
import os
import sys
import requests


file_dir = os.path.dirname('grid_geojson')
sys.path.append(file_dir)
from module.grid_geojson import *  # nopep8


# =============================================================================
# Full Interactive Grid
# =============================================================================


top_left_lon = 10.01129157249875
top_left_lat = 53.53380541749196

nrows = 78
ncols = 44

rotation = 145.5


cell_size = 16
crs_epsg = '31468'

properties = {
    'id': [i for i in range(nrows*ncols)],
    'usage': [0 for i in range(nrows*ncols)],
    'height': [5 for i in range(nrows*ncols)],
    'pop_density': [2 for i in range(nrows*ncols)]}
crs_epsg = '31468'

col_margin_left = 0  # columns to add to left of interactive grid to create full grid
row_margin_top = 0  # rows to add to top of interactive grid to create full grid


grasbrook_grid = Grid(top_left_lon, top_left_lat, rotation,
                      crs_epsg, cell_size, nrows, ncols)

grasbrook_grid.extend_int_grid_to_full(
    col_margin_left,  row_margin_top, nrows, ncols)

meta_map = json.dumps(grasbrook_grid.int_to_meta_map)


grid_geo = grasbrook_grid.get_grid_geojson(properties)

# Convert to string format
grid_geo_str = json.dumps(grid_geo)
f = open("meta_grid.json", "w+")
f.write(grid_geo_str)
f.close()

f = open("grid_map.json", "w+")
f.write(meta_map)
f.close()
```

**Comment by RELNO** [comment]
This is apparently not solved, as  `extend_int_grid_to_full` only makes ~1/2 of the cells active. This affects both the meta_grid and the mapping: 
<img width="683" alt="Screen Shot 2019-11-13 at 19 34 12" src="https://user-images.githubusercontent.com/14296774/68816632-071fe280-064d-11ea-923a-6dfeb8b3bb93.png">

**Comment by doorleyr** [comment]
I'm not sure how it ended with ~1/2 interactive cells. I would have to dig into your example a bit more. But there's now a working example here for (i) fully interactive and (ii) interactive region determined by the Land Use file (water areas have LU of 'None'): https://github.com/doorleyr/grid_geojson/blob/master/examples/grasbrook_grid_full_interactive.py

**Comment by RELNO** [comment]
Thanks. I'm actually suspecting it's not just 1/2, but that `extend_int_grid_to_full` somehow is looking to make a square instead of a free form rectangle.

**Comment by doorleyr** [comment]
The reason you had weird behaviour is you had the nrows (i.e. height) and ncols (i.e. width) arguments in the wrong order in the 'extend' function. So it tried to 'extend' to a smaller number of cells.
If you change to the following it works fine:
grasbrook_grid.extend_int_grid_to_full(col_margin_left,  row_margin_top, ncols, nrows)

Also, you mixed up the values for nrows and ncols. It should be:
nrows = 44
ncols = 78

And the point (53.53380541749196, 10.0112915724987) is the top-left corner of the small interactive area. It should be more like (53.537894, 10.006775).

The example file I linked to has everything correct.

**Comment by RELNO** [comment]
> And the point (53.53380541749196, 10.0112915724987) is the top-left corner of the small interactive area. It should be more like (53.537894, 10.006775).

Yes, in the attached screenshot I've already used the right starting point lat-long. 

In general, I'd suggest the library will default to fully active grids as they are much more common. So unless otherwise specified, the grid and map will be created with all active cells. Then, for special cases, a shapefile mapping should be applied:

![image](https://user-images.githubusercontent.com/14296774/68949467-19526b80-0788-11ea-90d1-fb5811156275.png)
